### ISSUE TITLE
QueryScaffolder should be able to set Connection::defaultLimit

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#115]
Currently, queries generated through the scaffolder are subject to the default limit of `Connection`. The user should be able to change this through the scaffolding layer.

## ACs
* As a developer, I want to be able to create a query using scaffolding that uses pagination with a limit that is not `100`

## Suggested change
```yaml
...
  paginate:
    limit: 25 # custom settings for the pagination

...
  paginate: false # no pagination


...
  paginate: true # pagination with default settings
```

## Tasks
- [ ] Update `QueryScaffolder` to accept configuration changes described above
- [ ] Update `QueryScaffolder` to accept a pagination limit via procedural code, e.g. `setPaginationLimit()`
- [ ] Throw when limit is set but pagination is `false`
- [ ] Refactor`QueryScaffolder` to apply applicable `paginate` settings to the `Connection` instance

**Comment by unclecheese** [comment]
Resolved https://github.com/silverstripe/silverstripe-graphql/pull/116
