### ISSUE TITLE
Multiple schema support

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#158]
Per research and discussion from: https://github.com/silverstripe/silverstripe-graphql/issues/156

## Acceptance Criteria
* I can create my own graphql endpoint and schema through configuration only (no code)
* My separate graphql schema provides markedly better response times than the alternative of putting all my types and operations into the current "default" schema
* I can keep the admin graphql schema behind authentication whilst providing my own public facing endpoint
* I can have a query, type, or mutation in my own schema that shares a name with the "default" schema, e.g. "readFiles"
* I can view and test both schemas with a single installation of `silverstripe-graphql-devtools`

## Tasks
- [ ] ~~Abstract `Manager` into a composable `SchemaInterface` service (with possible name change to `Schema` for concrete class)~~ (This ended up not making very much sense)
- [x] Make `Schema` an explicit dependency of `SilverStripe\GraphQL\Controller`
- [x] Allow `Schema` implementations to take their own config
- [x] Support a configuration-based collection of schemas (e.g. `SchemaRepository`)
- [x] Allow custom routing of GraphQL endpoints
- [x] Remap current `graphql/` endpoint to something more semantically correct, e.g. `admin/graphql`
- [x] Update file-based type caching (`types.graphql`) to support multiple schemas

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/169
- [x] #173 
- [x] #174 
- [x] https://github.com/silverstripe/recipe-cms/pull/18
- [x] https://github.com/silverstripe/recipe-cms/pull/19
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/806
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2211
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/566
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/167
- [x] https://github.com/silverstripe/silverstripe-graphql-devtools/pull/9

**Comment by chillu** [comment]
Another driver for multiple schemas: The CMS needs dynamic query execution (not statically analyseable at build time). But for unauthenticated frontend use of GraphQL, that's bad for two reasons:

 * Unrestricted query usage provides more attack surface due to query variations (or game any [query complexity restrictions](https://github.com/silverstripe/silverstripe-graphql/issues/15))
 * Complex queries could be considered not cacheable due to their length by HTTP caches, even in GET requests

The answer to this is persisted queries, as described here: https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5. Persisted query support would be easiest to enable on a different GraphQL endpoint with a different schema.

**Comment by maxime-rainville** [comment]
I merged what I could. I need someone else to review these PRs I have authored:
* #173
* #174
* silverstripe/recipe-cms#18
* silverstripe/recipe-cms#19

@unclecheese's other PRs are still running their build against `silverstripe/graphql` v2. We won't know for sure they are passing until the 4 PRs above are merged.

**Comment by robbieaverill** [comment]
@maxime-rainville I've merged those branching PRs and restarted the builds for the remaining open PRs. I'll leave the logic updates to you =)
