### ISSUE TITLE
GraphQL respects SilverStripe permissions

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#5]
As a website owner I want to users to have access only to the correct data

## Acceptance criteria

 * GraphQL queries fail if a user is not authenticated
 * Read request respect member-specific `canView()` restrictions
 * Mutation requests respect member-specific `canEdit()`, `canCreate()`, `canDelete()` restrictions

## Tasks

 * [x] ~~Enforce can*() methods on existing queries in asset-admin~~ (part of https://github.com/silverstripe/silverstripe-asset-admin/issues/316)
 * [x] Send human readable error as GraphQL [error message](http://facebook.github.io/graphql/#sec-Errors)
 * [x] Catch ValidationException and convert into a GraphQL [error message](http://facebook.github.io/graphql/#sec-Errors)

## Notes

 * Implement authentication (pass along `$member` into resolver context and use `can*()` methods there)

**Comment by wilr** [comment]
@chillu Tested and the existing errorHandler on Manager handles validationexceptions fine. Is there something else you expected it to handle?

**Comment by chillu** [comment]
Oh my, I've already done some of this back in September: https://github.com/silverstripe/silverstripe-graphql/commit/f9955b02695bbc983a0bf65597705ca294dfae30. Not at my brightest today, sorry Will...

I've ensured that `can*()` is enforced in all the queries we're creating as part of https://github.com/silverstripe/silverstripe-asset-admin/issues/316 (e.g. `Folder->canView()` is called on the object of a `parentId` filter), which should satisfy the acceptance criteria.

I'm closing this ticket, since the work is due to be merged shortly over in https://github.com/silverstripe/silverstripe-asset-admin/issues/316.
