### ISSUE TITLE
GraphQL Paginated Asset List

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#7]
As a user I want to read queries by page, so that I can open large folders.

## Acceptance criteria

 * Asset List View is migrated to use GraphQL for fetching data
 * Asset List view is paginated when data is pulled via GraphQL

## Tasks

 * [ ] Helper to create a connection from an ArrayList
 * [x] Node and edge types
 * [x] Default connection arguments for queries (start and limit)
 * [x] Unit tests for new helpers
 * [x] ~~Adapt asset pagination~~
 * [x] Update README with pagination example

Note: We could adapt the [graphql-php-relay Connection.php](https://github.com/ivome/graphql-relay-php/blob/master/src/Connection/Connection.php), but can't use it directly since it assumes a cursor-based pagination

## Research

Required for https://github.com/silverstripe/silverstripe-asset-admin/issues/159

There's two common approaches:
- Page number or offset pagination. More or less the standard.
- Cursor-based pagination. Great for fast changing data like social feeds, hence Relay mandates this approach. Can be implemented in the underlying PHP library via [graphql-relay-php](https://github.com/ivome/graphql-relay-php).

Read [graphql.org/learn/pagination](http://graphql.org/learn/pagination/) and [Understanding Pagination in GraphQL](https://dev-blog.apollodata.com/understanding-pagination-rest-graphql-and-relay-b10f835549e7#.mzuj6sxlp) for details.
- Relay only [supports](https://github.com/facebook/relay/issues/540) cursor based pagination, Apollo [supports](http://dev.apollodata.com/react/pagination.html) both. 
- Cursor-based pagination is probably overkill for our average CMS use case (data isn't changing that fast). 
- Offset-based pagination makes it harder to reference a particular view in an infinity scroll view (e.g. files in AssetAdmin) since offsets can change over time, but that's no different than 99% of webapps out there. It can easily be fixed by referencing a search result instead.
- By choosing offset-based pagination, we're making it harder to use a SilverStripe Content API with Relay (see [relay issue about offset-based pagination](https://github.com/facebook/relay/issues/540)). And since either pagination approach defines our "public API surface", it's going to be hard to change later.
- For custom data models, devs can choose to implement cursor-based pagination through applying [graphql-relay-php](https://github.com/ivome/graphql-relay-php) in their own resolvers.
- With offset-based pagination, you don't know if you've reached the end of the list unless you can pass back a total count (see [problem description](http://graphql.org/learn/pagination/#end-of-list-counts-and-connections)). In order to show client state based on total count (e.g. numbered pagination), we need nesting within our query responses anyway - what GraphQL calls a "connection object" (`{totalCount: 1, edges: [{id:99},{id:100}]}`). It's questionable if that's still good UX in 2016 though (as opposed to infinity/next-based pagination and powerful search), but cursor-based pagination lets us implement each UX.
- Cursors with custom ordering is explained in this [blog post](https://m.alphasights.com/how-to-do-effortless-pagination-with-relay-connections-and-graphql-ruby-a534ffaf5cbf#.aaeqxmwwb). In short, cursors encode a default sort order (`id---3` vs. `created_at---2016–02–02 02:40:27 UTC`). The average SS dev doesn't need to worry about these details, we can serialise it from the `DataList` query automatically.

~~Overall, while cursor-based pagination is a bit more convoluted in implementation and API signatures, I think it's the best way forward for us - most of this complexity will be abstracted away in the "graphql type scaffolder" (cursor encoding/decoding). I don't think there's much point in supporting multiple pagination approaches in SilverStripe's own APIs, although devs can always build offset-based pagination through the basic `graphql-php` building blocks (rather than the "graphql type scaffolder").~~

Update: We're recommending offset-based pagination as a quicker way to get this feature implemented, with some tradeoffs described in the [comments](https://github.com/chillu/silverstripe-graphql/issues/7#issuecomment-257185230)

**Comment by sminnee** [comment]
Let's start with offset-based pagination and Apollo. Adding cursor-based pagination will be hard now, or hard later, and it's not a priority to support Relay in SS4.

**Comment by sminnee** [comment]
I think that implementing cursor-based pagination in the SS ORM is a nice idea for SS5.

**Comment by sminnee** [comment]
Cursor-based pagination is something that MSSQL used and it was one of the worst things about dealing with it when we did the DB abstraction work.

Cursor-based pagination makes queries stateful which is a huge minefield. Cursor-based pagination makes a lot of sense for Facebook but it's not of much relevant for SilverStripe.

Cursor-based pagination isn't "the future", it's another approach with some nontrivial trade-offs. The only thing going for it is that it works with Relay, which we aren't using.

SilverStripe is built for offset-based pagination, cursors will be a lot more work, and I don't see a strong argument for cursors in SS4.

**Comment by chillu** [comment]
Talked to Sam a bit:

 * Cursors increase the potential for edge cases (e.g. two records with the same "created" timestamp). I think we can solve this by always sorting on `ID` as the least significant sort criteria though. 
 * Sam sees Cursors as part of the ORM rather than a GraphQL module feature, which increases its implementation complexity
 * Cursors can be opt-in for your own implementation
 * The fact that offset-based pagination makes Relay 1.x implementations harder for the next few months isn't a big factor for us (Relay 2.x will likely be less prescriptive around pagination)
 * Page-based pagination (with explicit page navigation) doesn't seem to be supported through Relay connections since you get the `totalCount`, but not all cursors for each page. This will make current approaches like `GridField` harder to implement.

So, I'm happy to implement offset-based pagination as a starting point, and leaving cursor-based pagination to SS5

**Comment by chillu** [comment]
I'm suggesting that we implement offset-paged pagination with the [Relay connection approach](https://facebook.github.io/relay/docs/graphql-connections.html#content), without cursors. It's a bit more verbose, but this way we can easily add cursors later. While cursors aren't essential for our use case, there's still fringe benefits of implemeting them: At the moment, GraphQL browsers like GraphiQL can't let you browse through data because there's no way to determine pagination vars. While other offset-based standards might evolve, it's safer for us to use the Relay structure.

Here's the example from the [GraphQL docs about Relay pagination](http://graphql.org/learn/pagination/):

```
{
  hero {
    name
    friendsConnection(first:2 after:"Y3Vyc29yMQ==") {
      totalCount
      edges {
        node {
          name
        }
        cursor
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
```

We would modify it by replacing the `start`/`after` params with `limit`/`offset`, removing the `node {cursor}` property, and adding a `totalCount`. Technically we could get rid of the `node` structure (since it only contains the record itself, not the `cursor`) - but that means we need to adapt every GraphQL query written for the SilverStripe Content API later on, rather than just layering more metadata on top of the existing implementation.

```
{
  hero {
    name
    friendsConnection(limit:10 offset:20) {
      totalCount
      edges {
        node {
          name
        }
      }
      pageInfo {
        totalCount
        hasNextPage
      }
    }
  }
}
```

**Comment by wilr** [comment]
Work has been under taken on https://github.com/silverstripe/silverstripe-graphql/tree/features/7-pagination. See example

![screen shot 2016-12-10 at 3 22 03 pm](https://cloud.githubusercontent.com/assets/101629/21070573/d0d8d54c-beec-11e6-851d-a99827c8739b.png)

**Comment by wilr** [comment]
@chillu Documentation and tests added.
